### ISSUE TITLE
Use of cwa-backlog repository

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-backlog#35] opened 2020-12-30 10:04 UTC
https://github.com/corona-warn-app/cwa-backlog#about-this-repository says:

"**About this Repository**
This repository contains future improvements of the Corona-Warn-App that will be implemented for the next app releases. Please note that this is not a complete backlog but a communication of a subset of planned extensions where we more or less know that they are coming."

In practice the repository is dormant and the last commit was in June 2020.

I suggest that the Open Source Team updates the [README.md](https://github.com/corona-warn-app/cwa-backlog/blob/master/README.md) according to the planned use of the repository including links about where to look for planned extensions.

This is related to the issue https://github.com/corona-warn-app/cwa-wishlist/issues/258.

--- 
Internal Tracking ID: [EXPOSUREAPP-4024](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4024)

**Comment by Ein-Tim** [comment] 2020-12-30 10:11
Related: https://github.com/corona-warn-app/cwa-wishlist/issues/274#issuecomment-736458272

**Comment by dsarkar** [comment] 2021-01-07 08:19
Internal Tracking ID: EXPOSUREAPP-4024

Thanks. DS

--- 
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-02-24 10:30
@dsarkar 
Did you come to any conclusion about this inactive repository?

**Comment by MikeMcC399** [comment] 2021-02-28 10:31
There is also a statement in the [Wishlist repository README.md](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md):

"Issues will be scanned regularly by members of the CWA Github organization and discussed with the product management and the RKI. If an issues is selected to be implemented in a future release of the Corona-Warn-App, it will be moved to the [CWA Backlog Repository](https://github.com/corona-warn-app/cwa-backlog)."

Clearly this process is not being followed.

**Comment by dsarkar** [comment] 2021-02-28 15:01
@MikeMcC399 True, we keep the issues in the repos where they were created. There is an internal discussion if this repo should be archived.

**Comment by dsarkar** [comment] 2021-03-29 14:32
- This repo will be archived (not deleted)
- All issues will be transferred to "active" repos. Reasons:
  - We keep usually all issues in their repo where they where created and do not transfer them anymore to the backlog repo
  - closed issues in an archived repo  can be read, but not re-oped or commented. Moving them to adequate repos maintains the possibility that the community can comment and re-open closed issues.
  - Labels "Fix" + release number will be used to indicate that there is a plan to fix the issue. This means that the issue is either still OPEN, ANALYZED, IN RPOGRESS, COMPLETED or CONFIRMED (i.e. tested)
  - Links to the issues in the backlog will not break, automatic re-direction to the new repo takes place.

All this should be mentioning (in a cleaner form) in the readme of the backlog repo.

**Comment by dsarkar** [comment] 2021-03-29 15:29
Actual readme (first item): 

<img width="828" alt="image" src="https://user-images.githubusercontent.com/1409741/112856713-60f14300-90b0-11eb-8133-170c0be4101c.png">

Suggestion: After title, before the existing paragraph:

This backlog repository is archived since xx/xx/2021. All issues, including the closed ones, have been transferred to "active" repositories, i.e. no issue has been lost. For reasons of transparency we archive this repository and do not delete it. Existing links to issues in the backlog will not break, automatic re-direction to the transferred issue in its  new repositories takes place.


Why is this repository archived? Now issues are usually taken care of  in the repository where they have been created. Since a longer time they have not been transferred to the backlog repository anymore. Keeping issues in the original repository has the advantage not mixing up Android, iOS, documentation, website, wish-list, and others issues.  

Archived repositories are read-only.  Closed issues in an archived repository can be read, but not re-opened or commented. Therefore, by having them transferred   to adequate repositories we keep the possibility that the community can comment and re-open closed issues if necessary.

Originally the backlog repository should indicate that it's containing  issues are in the pipeline of being solved. Instead, we now indicate in the "active" repositories with labels "Fix" + release number  that there is a plan to fix the issue. This means that the issue is either still OPEN, ANALYZED, IN RPOGRESS, COMPLETED or CONFIRMED (i.e. tested).


Original readme:
----
....

**Comment by MikeMcC399** [comment] 2021-03-29 15:58
@dsarkar 
This is a good decision. I have just a few suggestions for improvement with the English grammar. I can post them here, or you can open a PR and I can comment there.

**Comment by dsarkar** [comment] 2021-03-29 16:02
@MikeMcC399 Whatever you prefer. Either here or in a PR. Maybe the easiest is: Copy this text and modify it and re-post it. Let me know, what your preferred option is. Many thanks !

**Comment by MikeMcC399** [comment] 2021-03-29 16:26
@dsarkar 
I suggested quite a lot of changes! I hope that's OK with you. Feel free to accept or reject!


This backlog repository was archived on xx/xx/2021. All issues from the backlog repository, including the closed ones, have been transferred to active repositories, i.e. no issue has been lost. For reasons of transparency we have archived this repository in preference to deleting it. This allows previous links to issues in the backlog to continue to work, due to GitHub's automatic re-direction to the transferred issue in its new repository location.

Why has this repository been archived? For some time the backlog repository had not been used for its original purpose and instead issues are usually taken care of in the repository where they were created. Keeping issues in the original repository has the advantage of not mixing up Android, iOS, documentation, website and wish-list items together with other issues.

Archived repositories are read-only. Closed issues in an archived repository can be read, but not re-opened or commented on. Therefore, by transferring issues from the backlog repository to other active repositories we allow the community to comment and re-open closed issues if necessary.

Originally the backlog repository was intended to show issues in the pipeline of being solved. Instead, we now mark issues in the active repositories with labels "Fix" + release number to show that there is a plan to fix the issue. This means that the issue is either still OPEN, ANALYZED, IN PROGRESS, COMPLETED or CONFIRMED (i.e. tested).


Question: If an issue is OPEN could it already have a Fix label attached to it?

**Comment by dsarkar** [comment] 2021-03-29 16:38
@MikeMcC399 

> Question: If an issue is OPEN could it already have a Fix label attached to it?

Yes, because it is then included in the "Sprint" planning, but has not been assigned to a developer.

**Comment by dsarkar** [comment] 2021-03-29 16:42
@MikeMcC399 Fantastic help! Thanks!

**Comment by MikeMcC399** [comment] 2021-03-29 16:50
@dsarkar 

You're welcome! Maybe for the last sentence about the different status OPEN ... etc. add a bit more: 

This means that the issue has a corresponding internal development status which is one of OPEN, ANALYZED, IN PROGRESS, COMPLETED or CONFIRMED (i.e. tested). The Fix label stays with the issue even after the fix has been released and the issue has been closed.

**Comment by dsarkar** [comment] 2021-03-29 16:52
ANALYZING is the exact workflow label

**Comment by dsarkar** [comment] 2021-03-29 17:10
@MikeMcC399 

One last question: Do we bury this issue here, or would you like to move it to documents repo?

**Comment by MikeMcC399** [comment] 2021-03-29 17:33
@dsarkar 
I think this issue can stay in the backlog repository.

**Closed as completed** 2021-03-30 13:15 UTC
Labels: mirrored-to-jira
